### YamlMime:ManagedReference
items:
- uid: System.Data.ObjectNotFoundException
  id: ObjectNotFoundException
  children:
  - System.Data.ObjectNotFoundException.#ctor
  - System.Data.ObjectNotFoundException.#ctor(System.String)
  - System.Data.ObjectNotFoundException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: ObjectNotFoundException
  nameWithType: ObjectNotFoundException
  fullName: System.Data.ObjectNotFoundException
  type: Class
  summary: "개체가 없는 경우 throw 되는 예외입니다."
  remarks: "코드에서 예외를 처리 하는 방법에 대 한 자세한 내용은 <xref:System.Exception>.</xref:System.Exception> 을 참조 하십시오."
  syntax:
    content: 'public sealed class ObjectNotFoundException : System.Data.DataException'
  inheritance:
  - System.Exception
  - System.SystemException
  - System.Data.DataException
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Data.ObjectNotFoundException.#ctor
  id: '#ctor'
  parent: System.Data.ObjectNotFoundException
  langs:
  - csharp
  name: ObjectNotFoundException()
  nameWithType: ObjectNotFoundException.ObjectNotFoundException()
  fullName: System.Data.ObjectNotFoundException.ObjectNotFoundException()
  type: Constructor
  assemblies:
  - System.Data.Entity
  namespace: System.Data
  summary: "새 인스턴스를 초기화 <xref href=&quot;System.Data.ObjectNotFoundException&quot;> </xref>합니다."
  remarks: "코드에서 예외를 처리 하는 방법에 대 한 자세한 내용은 <xref:System.Exception>.</xref:System.Exception> 을 참조 하십시오."
  syntax:
    content: public ObjectNotFoundException ();
    parameters: []
  overload: System.Data.ObjectNotFoundException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Data.ObjectNotFoundException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Data.ObjectNotFoundException
  langs:
  - csharp
  name: ObjectNotFoundException(String)
  nameWithType: ObjectNotFoundException.ObjectNotFoundException(String)
  fullName: System.Data.ObjectNotFoundException.ObjectNotFoundException(String)
  type: Constructor
  assemblies:
  - System.Data.Entity
  namespace: System.Data
  summary: "새 인스턴스를 초기화 <xref href=&quot;System.Data.ObjectNotFoundException&quot;> </xref> 특수 한 오류 메시지를 사용 합니다."
  remarks: "코드에서 예외를 처리 하는 방법에 대 한 자세한 내용은 <xref:System.Exception>.</xref:System.Exception> 을 참조 하십시오."
  syntax:
    content: public ObjectNotFoundException (string message);
    parameters:
    - id: message
      type: System.String
      description: "오류를 설명 하는 메시지입니다."
  overload: System.Data.ObjectNotFoundException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Data.ObjectNotFoundException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Data.ObjectNotFoundException
  langs:
  - csharp
  name: ObjectNotFoundException(String,Exception)
  nameWithType: ObjectNotFoundException.ObjectNotFoundException(String,Exception)
  fullName: System.Data.ObjectNotFoundException.ObjectNotFoundException(String,Exception)
  type: Constructor
  assemblies:
  - System.Data.Entity
  namespace: System.Data
  summary: "새 인스턴스를 초기화 <xref href=&quot;System.Data.ObjectNotFoundException&quot;> </xref> 지정된 된 오류 메시지와 내부 예외에 대 한 참조를 사용 하는 클래스입니다."
  remarks: "코드에서 예외를 처리 하는 방법에 대 한 자세한 내용은 <xref:System.Exception>.</xref:System.Exception> 을 참조 하십시오."
  syntax:
    content: public ObjectNotFoundException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "오류를 설명 하는 메시지입니다."
    - id: innerException
      type: System.Exception
      description: "현재 예외 또는 null 참조의 원인이 되는 예외 (<xref uid=&quot;langword_csharp_Nothing&quot; name=&quot;Nothing&quot; href=&quot;&quot;> </xref> Visual basic에서) 내부 예외가 지정 되지 않은 경우."
  overload: System.Data.ObjectNotFoundException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Data.DataException
  isExternal: false
  name: System.Data.DataException
- uid: System.Data.ObjectNotFoundException.#ctor
  parent: System.Data.ObjectNotFoundException
  isExternal: false
  name: ObjectNotFoundException()
  nameWithType: ObjectNotFoundException.ObjectNotFoundException()
  fullName: System.Data.ObjectNotFoundException.ObjectNotFoundException()
- uid: System.Data.ObjectNotFoundException.#ctor(System.String)
  parent: System.Data.ObjectNotFoundException
  isExternal: false
  name: ObjectNotFoundException(String)
  nameWithType: ObjectNotFoundException.ObjectNotFoundException(String)
  fullName: System.Data.ObjectNotFoundException.ObjectNotFoundException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Data.ObjectNotFoundException.#ctor(System.String,System.Exception)
  parent: System.Data.ObjectNotFoundException
  isExternal: false
  name: ObjectNotFoundException(String,Exception)
  nameWithType: ObjectNotFoundException.ObjectNotFoundException(String,Exception)
  fullName: System.Data.ObjectNotFoundException.ObjectNotFoundException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Data.ObjectNotFoundException.#ctor*
  parent: System.Data.ObjectNotFoundException
  isExternal: false
  name: ObjectNotFoundException
  nameWithType: ObjectNotFoundException.ObjectNotFoundException
