### YamlMime:ManagedReference
items:
- uid: System.Runtime.Remoting.RemotingTimeoutException
  id: RemotingTimeoutException
  children:
  - System.Runtime.Remoting.RemotingTimeoutException.#ctor
  - System.Runtime.Remoting.RemotingTimeoutException.#ctor(System.String)
  - System.Runtime.Remoting.RemotingTimeoutException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: RemotingTimeoutException
  nameWithType: RemotingTimeoutException
  fullName: System.Runtime.Remoting.RemotingTimeoutException
  type: Class
  summary: "서버 또는 클라이언트는 이전에 지정 된 기간에 도달할 수 없는 경우 throw 되는 예외입니다."
  remarks: "RemotingTimeoutException 원격 호출이 지정 된 시간 제한 시간 내에 완료 되지 않을 때 throw 됩니다.       RemotingTimeoutException은 0x8013150B 값이 있는 HRESULT COR_E_REMOTING를 사용 합니다.       기본값을 사용 하 여 RemotingTimeoutException <xref:System.Object.Equals%2A>구현을 참조 일치를 지원 합니다.</xref:System.Object.Equals%2A>       RemotingTimeoutException의 인스턴스에 대 한 초기 속성 값 목록은 RemotingTimeoutException 생성자를 참조 합니다."
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      public class RemotingTimeoutException : System.Runtime.Remoting.RemotingException
  inheritance:
  - System.Exception
  - System.SystemException
  - System.Runtime.Remoting.RemotingException
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Runtime.Remoting.RemotingTimeoutException.#ctor
  id: '#ctor'
  parent: System.Runtime.Remoting.RemotingTimeoutException
  langs:
  - csharp
  name: RemotingTimeoutException()
  nameWithType: RemotingTimeoutException.RemotingTimeoutException()
  fullName: System.Runtime.Remoting.RemotingTimeoutException.RemotingTimeoutException()
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.Runtime.Remoting
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.Runtime.Remoting.RemotingTimeoutException&quot;> </xref> 클래스 기본 속성을 사용 합니다."
  remarks: "<xref:System.Runtime.Remoting.RemotingTimeoutException><xref:System.Exception>클래스</xref:System.Exception> 에서 상속</xref:System.Runtime.Remoting.RemotingTimeoutException> 다음 표에서 <xref:System.Runtime.Remoting.RemotingTimeoutException>클래스의 인스턴스에 대 한 초기 속성 값을 보여 줍니다: | 속성 | 값 |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| `null`|   | <xref:System.Exception.Message%2A>| <xref:System.Runtime.Remoting.RemotingTimeoutException>|</xref:System.Runtime.Remoting.RemotingTimeoutException> 에 대 한 지역화 된 오류 메시지</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A> </xref:System.Runtime.Remoting.RemotingTimeoutException>"
  syntax:
    content: public RemotingTimeoutException ();
    parameters: []
  overload: System.Runtime.Remoting.RemotingTimeoutException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Runtime.Remoting.RemotingTimeoutException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Runtime.Remoting.RemotingTimeoutException
  langs:
  - csharp
  name: RemotingTimeoutException(String)
  nameWithType: RemotingTimeoutException.RemotingTimeoutException(String)
  fullName: System.Runtime.Remoting.RemotingTimeoutException.RemotingTimeoutException(String)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.Runtime.Remoting
  summary: "새 인스턴스를 초기화 <xref href=&quot;System.Runtime.Remoting.RemotingTimeoutException&quot;> </xref> 지정 된 메시지 클래스입니다."
  remarks: "<xref:System.Runtime.Remoting.RemotingTimeoutException><xref:System.Exception>클래스</xref:System.Exception> 에서 상속</xref:System.Runtime.Remoting.RemotingTimeoutException> 다음 표에서 <xref:System.Runtime.Remoting.RemotingTimeoutException>클래스의 인스턴스에 대 한 초기 속성 값을 보여 줍니다: | 속성 형식 | 조건 |   |-------------------|---------------|   | <xref:System.Exception.InnerException%2A>| `null`|   | <xref:System.Exception.Message%2A>| `message` 문자열 |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A> </xref:System.Runtime.Remoting.RemotingTimeoutException>"
  syntax:
    content: public RemotingTimeoutException (string message);
    parameters:
    - id: message
      type: System.String
      description: "예외가 발생 한 원인을 나타내는 메시지입니다."
  overload: System.Runtime.Remoting.RemotingTimeoutException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Runtime.Remoting.RemotingTimeoutException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Runtime.Remoting.RemotingTimeoutException
  langs:
  - csharp
  name: RemotingTimeoutException(String,Exception)
  nameWithType: RemotingTimeoutException.RemotingTimeoutException(String,Exception)
  fullName: System.Runtime.Remoting.RemotingTimeoutException.RemotingTimeoutException(String,Exception)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.Runtime.Remoting
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.Runtime.Remoting.RemotingTimeoutException&quot;> </xref> 지정된 된 오류 메시지와 해당 예외의 원인인 내부 예외에 대 한 참조를 사용 하 여 클래스입니다."
  remarks: "이전 예외의 직접적인 결과에 이전 예외에 대 한 참조를 포함 해야 throw 되는 예외는 <xref:System.Exception.InnerException%2A>속성.</xref:System.Exception.InnerException%2A> <xref:System.Exception.InnerException%2A>속성은 생성자에 전달 되는 동일한 값을 반환 하거나 `null` 경우는 <xref:System.Exception.InnerException%2A>생성자에 내부 예외 값을 제공 하지 않는.</xref:System.Exception.InnerException%2A> </xref:System.Exception.InnerException%2A>       다음 표에서 <xref:System.Runtime.Remoting.RemotingTimeoutException>클래스의 인스턴스에 대 한 초기 속성 값을 보여 줍니다: | 속성 | 값 |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| 내부 예외 참조 |   | <xref:System.Exception.Message%2A>| 오류 메시지 문자열 |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A> </xref:System.Runtime.Remoting.RemotingTimeoutException>"
  syntax:
    content: public RemotingTimeoutException (string message, Exception InnerException);
    parameters:
    - id: message
      type: System.String
      description: "예외에 대 한 이유를 설명 하는 오류 메시지입니다."
    - id: InnerException
      type: System.Exception
      description: "현재 예외의 원인인 예외입니다. 경우는 `InnerException` 매개 변수가 않습니다 <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>에서 현재 예외가 발생 한 <xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;> </xref> 내부 예외를 처리 하는 블록입니다."
  overload: System.Runtime.Remoting.RemotingTimeoutException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Runtime.Remoting.RemotingException
  isExternal: false
  name: System.Runtime.Remoting.RemotingException
- uid: System.Runtime.Remoting.RemotingTimeoutException.#ctor
  parent: System.Runtime.Remoting.RemotingTimeoutException
  isExternal: false
  name: RemotingTimeoutException()
  nameWithType: RemotingTimeoutException.RemotingTimeoutException()
  fullName: System.Runtime.Remoting.RemotingTimeoutException.RemotingTimeoutException()
- uid: System.Runtime.Remoting.RemotingTimeoutException.#ctor(System.String)
  parent: System.Runtime.Remoting.RemotingTimeoutException
  isExternal: false
  name: RemotingTimeoutException(String)
  nameWithType: RemotingTimeoutException.RemotingTimeoutException(String)
  fullName: System.Runtime.Remoting.RemotingTimeoutException.RemotingTimeoutException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Runtime.Remoting.RemotingTimeoutException.#ctor(System.String,System.Exception)
  parent: System.Runtime.Remoting.RemotingTimeoutException
  isExternal: false
  name: RemotingTimeoutException(String,Exception)
  nameWithType: RemotingTimeoutException.RemotingTimeoutException(String,Exception)
  fullName: System.Runtime.Remoting.RemotingTimeoutException.RemotingTimeoutException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Runtime.Remoting.RemotingTimeoutException.#ctor*
  parent: System.Runtime.Remoting.RemotingTimeoutException
  isExternal: false
  name: RemotingTimeoutException
  nameWithType: RemotingTimeoutException.RemotingTimeoutException
