### YamlMime:ManagedReference
items:
- uid: System.Runtime.Remoting.RemotingException
  id: RemotingException
  children:
  - System.Runtime.Remoting.RemotingException.#ctor
  - System.Runtime.Remoting.RemotingException.#ctor(System.String)
  - System.Runtime.Remoting.RemotingException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Runtime.Remoting.RemotingException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: RemotingException
  nameWithType: RemotingException
  fullName: System.Runtime.Remoting.RemotingException
  type: Class
  summary: "오류가 발생 했는지 원격 작업 동안 한 경우 throw 되는 예외입니다."
  remarks: "RemotingException은 0x8013150B 값이 있는 HRESULT COR_E_REMOTING를 사용 합니다.       기본값을 사용 하 여 RemotingException <xref:System.Object.Equals%2A>구현을 참조 일치를 지원 합니다.</xref:System.Object.Equals%2A>       RemotingException의 인스턴스에 대 한 초기 속성 값 목록은 RemotingException 생성자를 참조 합니다."
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      public class RemotingException : SystemException
  inheritance:
  - System.Exception
  - System.SystemException
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Runtime.Remoting.RemotingException.#ctor
  id: '#ctor'
  parent: System.Runtime.Remoting.RemotingException
  langs:
  - csharp
  name: RemotingException()
  nameWithType: RemotingException.RemotingException()
  fullName: System.Runtime.Remoting.RemotingException.RemotingException()
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.Runtime.Remoting
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.Runtime.Remoting.RemotingException&quot;> </xref> 클래스 기본 속성을 사용 합니다."
  remarks: "<xref:System.Runtime.Remoting.RemotingException><xref:System.SystemException>클래스</xref:System.SystemException> 에서 상속</xref:System.Runtime.Remoting.RemotingException> 다음 표에서 <xref:System.Runtime.Remoting.RemotingException>클래스의 인스턴스에 대 한 초기 속성 값을 보여 줍니다: | 속성 | 값 |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| `null`|   | <xref:System.Exception.Message%2A>| 빈 문자열 (&quot;&quot;) |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A> </xref:System.Runtime.Remoting.RemotingException>"
  syntax:
    content: public RemotingException ();
    parameters: []
  overload: System.Runtime.Remoting.RemotingException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Runtime.Remoting.RemotingException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Runtime.Remoting.RemotingException
  langs:
  - csharp
  name: RemotingException(String)
  nameWithType: RemotingException.RemotingException(String)
  fullName: System.Runtime.Remoting.RemotingException.RemotingException(String)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.Runtime.Remoting
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.Runtime.Remoting.RemotingException&quot;> </xref> 지정 된 메시지 클래스입니다."
  remarks: "<xref:System.Runtime.Remoting.RemotingException><xref:System.SystemException>클래스</xref:System.SystemException> 에서 상속</xref:System.Runtime.Remoting.RemotingException> 다음 표에서 <xref:System.Runtime.Remoting.RemotingException>클래스의 인스턴스에 대 한 초기 속성 값을 보여 줍니다: | 속성 형식 | 조건 |   |-------------------|---------------|   | <xref:System.Exception.InnerException%2A>| `null`|   | <xref:System.Exception.Message%2A>| `message` 문자열 |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A> </xref:System.Runtime.Remoting.RemotingException>"
  syntax:
    content: public RemotingException (string message);
    parameters:
    - id: message
      type: System.String
      description: "예외가 발생 한 이유를 설명 하는 오류 메시지입니다."
  overload: System.Runtime.Remoting.RemotingException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Runtime.Remoting.RemotingException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Runtime.Remoting.RemotingException
  langs:
  - csharp
  name: RemotingException(SerializationInfo,StreamingContext)
  nameWithType: RemotingException.RemotingException(SerializationInfo,StreamingContext)
  fullName: System.Runtime.Remoting.RemotingException.RemotingException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.Runtime.Remoting
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.Runtime.Remoting.RemotingException&quot;> </xref> serialize 된 데이터에서 클래스입니다."
  remarks: "이 생성자는 스트림을 통해 전송 된 예외 개체를 다시 구성 하기 위해 역직렬화 하는 동안 호출 됩니다. (Serialization 중에 대 한 자세한 내용은 참조 하십시오. [XML 및 SOAP Serialization](~/add/includes/ajax-current-ext-md.md).)"
  syntax:
    content: protected RemotingException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "직렬화 된 개체 데이터를 보유 하는 개체입니다."
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "소스 또는 대상의 예외에 대 한 컨텍스트 정보입니다."
  overload: System.Runtime.Remoting.RemotingException.#ctor*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "The <code>info</code> parameter is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  platform:
  - net462
- uid: System.Runtime.Remoting.RemotingException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Runtime.Remoting.RemotingException
  langs:
  - csharp
  name: RemotingException(String,Exception)
  nameWithType: RemotingException.RemotingException(String,Exception)
  fullName: System.Runtime.Remoting.RemotingException.RemotingException(String,Exception)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.Runtime.Remoting
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.Runtime.Remoting.RemotingException&quot;> </xref> 지정된 된 오류 메시지와 해당 예외의 원인인 내부 예외에 대 한 참조를 사용 하 여 클래스입니다."
  remarks: "에 이전 예외에 대 한 참조를 포함할 됩니다 이전 예외의 직접적인 결과로 throw 되는 예외는 <xref:System.Exception.InnerException%2A>속성.</xref:System.Exception.InnerException%2A> <xref:System.Exception.InnerException%2A>속성은 생성자에 전달 되는 동일한 값을 반환 하거나 `null` 경우는 <xref:System.Exception.InnerException%2A>생성자에 내부 예외 값을 제공 하지 않는.</xref:System.Exception.InnerException%2A> </xref:System.Exception.InnerException%2A>       다음 표에서 <xref:System.Runtime.Remoting.RemotingException>클래스의 인스턴스에 대 한 초기 속성 값을 보여 줍니다: | 속성 | 값 |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| 내부 예외를 참조 합니다. |   | <xref:System.Exception.Message%2A>| 오류 메시지 문자열입니다. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A> </xref:System.Runtime.Remoting.RemotingException>"
  syntax:
    content: public RemotingException (string message, Exception InnerException);
    parameters:
    - id: message
      type: System.String
      description: "예외가 발생 한 이유를 설명 하는 오류 메시지입니다."
    - id: InnerException
      type: System.Exception
      description: "현재 예외의 원인인 예외입니다. 경우는 `InnerException` 매개 변수가 않습니다 <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>에서 현재 예외가 발생 한 <xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;> </xref> 내부 예외를 처리 하는 블록입니다."
  overload: System.Runtime.Remoting.RemotingException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.SystemException
  isExternal: false
  name: System.SystemException
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.Runtime.Remoting.RemotingException.#ctor
  parent: System.Runtime.Remoting.RemotingException
  isExternal: false
  name: RemotingException()
  nameWithType: RemotingException.RemotingException()
  fullName: System.Runtime.Remoting.RemotingException.RemotingException()
- uid: System.Runtime.Remoting.RemotingException.#ctor(System.String)
  parent: System.Runtime.Remoting.RemotingException
  isExternal: false
  name: RemotingException(String)
  nameWithType: RemotingException.RemotingException(String)
  fullName: System.Runtime.Remoting.RemotingException.RemotingException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Runtime.Remoting.RemotingException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Runtime.Remoting.RemotingException
  isExternal: false
  name: RemotingException(SerializationInfo,StreamingContext)
  nameWithType: RemotingException.RemotingException(SerializationInfo,StreamingContext)
  fullName: System.Runtime.Remoting.RemotingException.RemotingException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Runtime.Remoting.RemotingException.#ctor(System.String,System.Exception)
  parent: System.Runtime.Remoting.RemotingException
  isExternal: false
  name: RemotingException(String,Exception)
  nameWithType: RemotingException.RemotingException(String,Exception)
  fullName: System.Runtime.Remoting.RemotingException.RemotingException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Runtime.Remoting.RemotingException.#ctor*
  parent: System.Runtime.Remoting.RemotingException
  isExternal: false
  name: RemotingException
  nameWithType: RemotingException.RemotingException
