### YamlMime:ManagedReference
items:
- uid: System.IO.IsolatedStorage.IsolatedStorageException
  id: IsolatedStorageException
  children:
  - System.IO.IsolatedStorage.IsolatedStorageException.#ctor
  - System.IO.IsolatedStorage.IsolatedStorageException.#ctor(System.String)
  - System.IO.IsolatedStorage.IsolatedStorageException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.IO.IsolatedStorage.IsolatedStorageException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: IsolatedStorageException
  nameWithType: IsolatedStorageException
  fullName: System.IO.IsolatedStorage.IsolatedStorageException
  type: Class
  summary: "격리 된 저장소에서 작업이 실패 하면 throw 되는 예외입니다."
  remarks: "`IsolatedStorageException`0x80131450 값이 있는 HRESULT ISS_E_ISOSTORE를 사용 합니다.       격리 된 저장소 예외의 가장 일반적인 예는 다음과 같습니다.      -누락 된 증명 정보입니다. 격리 된 저장소는 증명 정보 (어셈블리 및 해당 원본에 대 한 정보)는 코드의 id를 확인 하 고 올바른 관련된 파일 공간에 연결 하기 위해 필요 합니다. 이 정보가 없으면 격리 된 저장소를 사용할 수 없습니다.      -잘못 된 작업입니다. 일부 <xref:System.IO.FileStream>격리 된 저장소에 대 한 작업이 지원 되지 않습니다.</xref:System.IO.FileStream>       인스턴스에 대 한 초기 속성 값 목록은 `IsolatedStorageException`, 참조는 <xref:System.IO.IsolatedStorage.IsolatedStorageException.%23ctor%2A>생성자.</xref:System.IO.IsolatedStorage.IsolatedStorageException.%23ctor%2A>"
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      public class IsolatedStorageException : Exception
  inheritance:
  - System.Exception
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.IO.IsolatedStorage.IsolatedStorageException.#ctor
  id: '#ctor'
  parent: System.IO.IsolatedStorage.IsolatedStorageException
  langs:
  - csharp
  name: IsolatedStorageException()
  nameWithType: IsolatedStorageException.IsolatedStorageException()
  fullName: System.IO.IsolatedStorage.IsolatedStorageException.IsolatedStorageException()
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.IO.IsolatedStorage
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.IO.IsolatedStorage.IsolatedStorageException&quot;> </xref> 클래스 기본 속성을 사용 합니다."
  remarks: "다음 표에서 <xref:System.IO.IsolatedStorage.IsolatedStorageException>안내 하십시오.</xref:System.IO.IsolatedStorage.IsolatedStorageException> 인스턴스에 대 한 초기 속성 값을 보여 줍니다.      | 속성 | 값 |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| `null`.|   | <xref:System.Exception.Message%2A>| 지역화 된 오류 메시지 문자열입니다. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public IsolatedStorageException ();
    parameters: []
  overload: System.IO.IsolatedStorage.IsolatedStorageException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.IO.IsolatedStorage.IsolatedStorageException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.IO.IsolatedStorage.IsolatedStorageException
  langs:
  - csharp
  name: IsolatedStorageException(String)
  nameWithType: IsolatedStorageException.IsolatedStorageException(String)
  fullName: System.IO.IsolatedStorage.IsolatedStorageException.IsolatedStorageException(String)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.IO.IsolatedStorage
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.IO.IsolatedStorage.IsolatedStorageException&quot;> </xref> 지정된 된 오류 메시지를 사용 하 여 클래스입니다."
  remarks: "다음 표에서 <xref:System.IO.IsolatedStorage.IsolatedStorageException>안내 하십시오.</xref:System.IO.IsolatedStorage.IsolatedStorageException> 인스턴스에 대 한 초기 속성 값을 보여 줍니다.      | 속성 | 값 |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| `null`.|   | <xref:System.Exception.Message%2A>| 오류 메시지 문자열입니다. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public IsolatedStorageException (string message);
    parameters:
    - id: message
      type: System.String
      description: "예외에 대 한 이유를 설명 하는 오류 메시지입니다."
  overload: System.IO.IsolatedStorage.IsolatedStorageException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.IO.IsolatedStorage.IsolatedStorageException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.IO.IsolatedStorage.IsolatedStorageException
  langs:
  - csharp
  name: IsolatedStorageException(SerializationInfo,StreamingContext)
  nameWithType: IsolatedStorageException.IsolatedStorageException(SerializationInfo,StreamingContext)
  fullName: System.IO.IsolatedStorage.IsolatedStorageException.IsolatedStorageException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.IO.IsolatedStorage
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.IO.IsolatedStorage.IsolatedStorageException&quot;> </xref> serialize 된 데이터 클래스입니다."
  remarks: "이 생성자는 스트림을 통해 전송 된 예외 개체를 다시 구성 하기 위해 역직렬화 하는 동안 호출 됩니다."
  syntax:
    content: protected IsolatedStorageException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "직렬화 된 개체 데이터를 보유 하는 개체입니다."
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "소스 또는 대상에 대 한 컨텍스트 정보입니다."
  overload: System.IO.IsolatedStorage.IsolatedStorageException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.IO.IsolatedStorage.IsolatedStorageException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.IO.IsolatedStorage.IsolatedStorageException
  langs:
  - csharp
  name: IsolatedStorageException(String,Exception)
  nameWithType: IsolatedStorageException.IsolatedStorageException(String,Exception)
  fullName: System.IO.IsolatedStorage.IsolatedStorageException.IsolatedStorageException(String,Exception)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.IO.IsolatedStorage
  summary: "새 인스턴스를 초기화는 <xref href=&quot;System.IO.IsolatedStorage.IsolatedStorageException&quot;> </xref> 지정된 된 오류 메시지와 해당 예외의 원인인 내부 예외에 대 한 참조를 사용 하 여 클래스입니다."
  remarks: "이전 예외의 직접적인 결과에 이전 예외에 대 한 참조가 들어 있어야 throw 되는 예외는 <xref:System.Exception.InnerException%2A>속성.</xref:System.Exception.InnerException%2A> <xref:System.Exception.InnerException%2A>속성은 생성자에 전달 되는 동일한 값을 반환 하거나 `null` 경우는 <xref:System.Exception.InnerException%2A>생성자에 내부 예외 값을 제공 하지 않는.</xref:System.Exception.InnerException%2A> </xref:System.Exception.InnerException%2A>       다음 표에서 <xref:System.IO.IsolatedStorage.IsolatedStorageException>안내 하십시오.</xref:System.IO.IsolatedStorage.IsolatedStorageException> 인스턴스에 대 한 초기 속성 값을 보여 줍니다.      | 속성 | 값 |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| 내부 예외를 참조 합니다. |   | <xref:System.Exception.Message%2A>| 오류 메시지 문자열입니다. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public IsolatedStorageException (string message, Exception inner);
    parameters:
    - id: message
      type: System.String
      description: "예외에 대 한 이유를 설명 하는 오류 메시지입니다."
    - id: inner
      type: System.Exception
      description: "현재 예외의 원인인 예외입니다. 경우는 `inner` 매개 변수가 않습니다 <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>에서 현재 예외가 발생 한 <xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;> </xref> 내부 예외를 처리 하는 블록입니다."
  overload: System.IO.IsolatedStorage.IsolatedStorageException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Exception
  isExternal: false
  name: System.Exception
- uid: System.IO.IsolatedStorage.IsolatedStorageException.#ctor
  parent: System.IO.IsolatedStorage.IsolatedStorageException
  isExternal: false
  name: IsolatedStorageException()
  nameWithType: IsolatedStorageException.IsolatedStorageException()
  fullName: System.IO.IsolatedStorage.IsolatedStorageException.IsolatedStorageException()
- uid: System.IO.IsolatedStorage.IsolatedStorageException.#ctor(System.String)
  parent: System.IO.IsolatedStorage.IsolatedStorageException
  isExternal: false
  name: IsolatedStorageException(String)
  nameWithType: IsolatedStorageException.IsolatedStorageException(String)
  fullName: System.IO.IsolatedStorage.IsolatedStorageException.IsolatedStorageException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.IO.IsolatedStorage.IsolatedStorageException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.IO.IsolatedStorage.IsolatedStorageException
  isExternal: false
  name: IsolatedStorageException(SerializationInfo,StreamingContext)
  nameWithType: IsolatedStorageException.IsolatedStorageException(SerializationInfo,StreamingContext)
  fullName: System.IO.IsolatedStorage.IsolatedStorageException.IsolatedStorageException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.IO.IsolatedStorage.IsolatedStorageException.#ctor(System.String,System.Exception)
  parent: System.IO.IsolatedStorage.IsolatedStorageException
  isExternal: false
  name: IsolatedStorageException(String,Exception)
  nameWithType: IsolatedStorageException.IsolatedStorageException(String,Exception)
  fullName: System.IO.IsolatedStorage.IsolatedStorageException.IsolatedStorageException(String,Exception)
- uid: System.IO.IsolatedStorage.IsolatedStorageException.#ctor*
  parent: System.IO.IsolatedStorage.IsolatedStorageException
  isExternal: false
  name: IsolatedStorageException
  nameWithType: IsolatedStorageException.IsolatedStorageException
